### ISSUE TITLE
Persistent re-spawn mission requirements.

### ISSUE THREAD

**Issue by Bergfinn** [14aag/mission_template#1]
When running main operation maps and you want to run our persistence you need to make sure to have placed down the standard respawn_west Empty marker. 

On top of that you'll need a empty marker with respawn_whatever for each group that might exist. In our current setup that means HQ(Allfather), SOAR, VIKING 1 and VIKING 2. So you'd end up with a respawn marker for each. See image for reference. 

![nAObue5](https://user-images.githubusercontent.com/55322180/66270740-39bd0b00-e857-11e9-9a3d-d2d80459ae19.png)

**Comment by ghost** [comment]
@Bergfinn should I add this to the wiki?

**Comment by zharf** [comment]
The requirements have changed a little bit for this actually, you don't need the respawn markers anymore
